apiVersion: v1
kind: Template

labels:
  application: demo-admin

metadata:
  name: demo-admin

parameters:
  - name: SECRET_NAME
    value: 2020-demo-admin
    required: true
  - name: CONFIG_MAP_NAME
    value: 2020-demo-admin
    required: true
  - name: ADMIN_PASSWORD
    value: ""
  - name: DATAGRID_HOST
    value: datagrid-service.datagrid-demo.svc.cluster.local
    required: true
  - name: DATAGRID_HOTROD_PORT
    value: "11222"
    required: true
  - name: LEADERBOARD_URL
    value: "http://leaderboard-api.leaderboard.svc.cluster.local:8080"
    required: true
  - name: CLUSTER_NAME
    value: 'HQ'
    required: true


objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
    data:
    stringData:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${CONFIG_MAP_NAME}
    data:
      DATAGRID_HOST: ${DATAGRID_HOST}
      DATAGRID_HOTROD_PORT: ${DATAGRID_HOTROD_PORT}
      LEADERBOARD_URL: ${LEADERBOARD_URL}
      CLUSTER_NAME: ${CLUSTER_NAME}
