apiVersion: v1
kind: Template

metadata:
  name: leaderboard-aggregator

parameters:
  - name: APPLICATION_NAME
    required: true
  - name: KAFKA_STREAMS_TOPIC
    required: true
  - name: ROUTE_NAME
    value: leaderboard-aggregator
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: PG_SECRET
    value: openshift-pgsql12-primary-secret
    required: true
  - name: IMAGE_REPOSITORY
    displayName: Image Repository
    value: quay.io/redhatdemo/2020-leaderboard-aggregator:latest
    required: true
  - name: CONTAINER_REQUEST_CPU
    value: "500m"
  - name: CONTAINER_REQUEST_MEMORY
    value: "500Mi"
  - name: CONTAINER_LIMIT_CPU
    value: "2"
  - name: CONTAINER_LIMIT_MEMORY
    value: "2Gi"

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APPLICATION_NAME}
        app.kubernetes.io/part-of: leaderboard-streams
      name: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 2
      selector:
        app: ${APPLICATION_NAME}
      strategy:
        rollingParams:
          timeoutSeconds: 3600
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            topic: ${KAFKA_STREAMS_TOPIC}
        spec:
          containers:
            - image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: aggregator
              env:
                - name: QUARKUS_KAFKA_STREAMS_APPLICATION_ID
                  value: ${APPLICATION_NAME}
                - name: QUARKUS_KAFKA_STREAMS_TOPICS
                  value: ${KAFKA_STREAMS_TOPIC}
                - name: QUARKUS_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${PG_SECRET}
                      key: database-username
                - name: QUARKUS_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${PG_SECRET}
                      key: database-username-password
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CONTAINER_REQUEST_CPU}
                  memory: ${CONTAINER_REQUEST_MEMORY}
                limits:
                  cpu: ${CONTAINER_LIMIT_CPU}
                  memory: ${CONTAINER_LIMIT_MEMORY}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            from:
              kind: ImageStreamTag
              name: 2020-leaderboard-aggregator:latest
            containerNames:
              - "aggregator"
