---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: rollout-latest-aggregator
spec:
  params:
    - name: "applicationSrcDir"
  check:
    # TODO update to UBI
    image: alpine
    script: '[[ "$(params.applicationSrcDir)" = "leaderboard-aggregator" ]] && echo "Rollout latest Leaderboard Aggregator"'
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: rollout-latest-api
spec:
  params:
    - name: "applicationSrcDir"
  check:
    # TODO update to UBI
    image: alpine
    script: '[[ "$(params.applicationSrcDir)" = "leaderboard-api" ]] && echo "Rollout latest Leaderboard API"'
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: leaderboard-deploy
spec:
  resources:
    - name: app-source
      type: git
    - name: app-image
      type: image
  params:
    - name: applicationSrcDir
      description: The source directory of the application within the source repository
    - name: mavenMirrorUrl
      description: The maven mirror to use
      default: https://repo1.maven.apache.org
    - name: dockerFile
      description: Parameter Description
      default: Dockerfile.jvm
  tasks:
    - name: build
      taskRef:
        name: build-quarkus-app
      resources:
        inputs:
          - name: source
            resource: app-source
        outputs:
          - name: builtImage
            resource: app-image
      params:
        - name: contextDir
          value: "$(params.applicationSrcDir)"
        - name: mavenMirrorUrl
          value: "$(params.mavenMirrorUrl)"
        - name: dockerFile
          value: "$(params.dockerFile)"
    - name: import-leaderboard-is
      conditions:
        - conditionRef: rollout-latest-aggregator
          params:
            - name: "applicationSrcDir"
              value: "$(params.applicationSrcDir)"
      taskRef:
        name: oc-import-image
        kind: Task
      resources:
        inputs:
          - name: appImage
            resource: app-image
            from:
              - build
      params:
        - name: imageStreamName
          value: "2020-leaderboard-aggregator"
    - name: import-leaderboard-api-is
      conditions:
        - conditionRef: rollout-latest-api
          params:
            - name: "applicationSrcDir"
              value: "$(params.applicationSrcDir)"
      taskRef:
        name: oc-import-image
        kind: Task
      resources:
        inputs:
          - name: appImage
            resource: app-image
            from:
              - build
      params:
        - name: imageStreamName
          value: "2020-leaderboard-api"
