apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leaderboard-broadcast
    app.kubernetes.io/part-of: leaderboard-messaging
  name: leaderboard-broadcast
spec:
  replicas: ${LEADERBOARD_BROADCAST_REPLICAS}
  selector:
    matchLabels:
      app: leaderboard-broadcast
  template:
    metadata:
      labels:
        app: leaderboard-broadcast
    spec:
      containers:
        - image: ${LEADERBOARD_BROADCAST_IMAGE}
          imagePullPolicy: Always
          name: broadcast
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${PG_SECRET}
                  key: database-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${PG_SECRET}
                  key: database-username-password
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          resources:
            requests:
              cpu: "150m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "200Mi"
          volumeMounts:
            - mountPath: /etc/messaging
              name: skupper-amqp-trust
      volumes:
        - name: skupper-amqp-trust
          secret:
            secretName: skupper
