apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leaderboard-api
    app.kubernetes.io/part-of: leaderboard-backend
  name: leaderboard-api
spec:
  replicas: ${LEADERBOARD_API_REPLICAS}
  selector:
    matchLabels:
      app: leaderboard-api
  template:
    metadata:
      labels:
        app: leaderboard-api
    spec:
      containers:
        - image: ${LEADERBOARD_API_IMAGE}
          imagePullPolicy: Always
          name: api
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${PG_SECRET}
                  key: database-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${PG_SECRET}
                  key: database-username-password
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          volumeMounts:
            - mountPath: /etc/messaging
              name: skupper-amqp-trust
      volumes:
        - name: skupper-amqp-trust
          secret:
            secretName: skupper
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: leaderboard-api
  name: leaderboard-api
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: leaderboard-api
