---
kind: Secret
apiVersion: v1
metadata:
  name: openshift-pgsql12-primary-secret
stringData:
  database-db: "gamedb"
  database-username: "$PGSQL12_USERNAME"
  database-username-password: "$PGSQL12_PASSWORD"
