---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: rollout-latest-aggregator
spec:
  params:
    - name: "applicationSrcDir"
  check:
    # TODO update to UBI
    image: registry.access.redhat.com/ubi8/ubi-minimal:8.1
    script: '[[ "$(params.applicationSrcDir)" = "leaderboard-aggregator" ]] && echo "Rollout latest Leaderboard Aggregator"'
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: rollout-latest-api
spec:
  params:
    - name: "applicationSrcDir"
  check:
    # TODO update to UBI
    image: registry.access.redhat.com/ubi8/ubi-minimal:8.1
    script: '[[ "$(params.applicationSrcDir)" = "leaderboard-api" ]] && echo "Rollout latest Leaderboard API"'
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: rollout-latest-broadcast
spec:
  params:
    - name: "applicationSrcDir"
  check:
    # TODO update to UBI
    image: registry.access.redhat.com/ubi8/ubi-minimal:8.1
    script: '[[ "$(params.applicationSrcDir)" = "leaderboard-broadcast" ]] && echo "Rollout latest Leaderboard Broadcast"'
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: rollout-latest-messaging
spec:
  params:
    - name: "applicationSrcDir"
  check:
    # TODO update to UBI
    image: registry.access.redhat.com/ubi8/ubi-minimal:8.1
    script: '[[ "$(params.applicationSrcDir)" = "leaderboard-messaging" ]] && echo "Rollout latest Leaderboard Messaging"'
